_wandb:
    value:
        cli_version: 0.21.2
        e:
            rozcmbnw9izb1uenbnrcecry6clhjsrb:
                codePath: cs336_basics/train/train_transformerLM.py
                codePathLocal: train_transformerLM.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "344847360000"
                email: 1280773543@qq.com
                executable: /home/niu/code/cs336/assignment1-basics/.venv/bin/python3
                git:
                    commit: d555b2bee9b7fd5fb47c989b35bda2c0b5039f7a
                    remote: git@github.com:NiuHuangxiaozi/assignment1-basics.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-975ac2df-a656-7f31-f14c-25e0a5ef8651
                host: DESKTOP-SF42OLM
                memory:
                    total: "8175075328"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/niu/code/cs336/assignment1-basics/cs336_basics/train/train_transformerLM.py
                python: CPython 3.12.7
                root: /home/niu/code/cs336/assignment1-basics/cs336_basics/train
                startedAt: "2025-11-06T18:08:03.959009Z"
                writerId: rozcmbnw9izb1uenbnrcecry6clhjsrb
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 61
            "4": 3.12.7
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 96
beta1:
    value: 0.9
beta2:
    value: 0.999
context_length:
    value: 256
cosine_cycle_steps:
    value: 8000
epochs:
    value: 2
eps:
    value: 1e-08
learning_rate:
    value: 0.0001
learning_rate_min:
    value: 1e-05
max_norm:
    value: 1
optimizer:
    value: AdamW
warmup_steps:
    value: 2000
weight_decay:
    value: 0.01
